# Generated by Django 4.0.1 on 2022-01-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-add_date']},
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
