# Generated by Django 4.0.1 on 2022-01-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.TextField(max_length=100),
        ),
    ]
