# Generated by Django 4.0.1 on 2022-01-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_category_url_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
