# Generated by Django 4.0.1 on 2022-02-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_remove_profile_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogviews',
            field=models.IntegerField(default=0),
        ),
    ]
